### ISSUE TITLE
Some sentences should come as quote

### ISSUE THREAD

**Issue by dangsonbk** [ZuzooVn/machine-learning-for-software-engineers#41]
Honestly I think you should use quote mark for some sentences in the [Why use it? ](https://github.com/ZuzooVn/machine-learning-for-software-engineers#why-use-it) part when you copy those from the answer in above link.
Anyway, it's an awesome list; :)

**Comment by ZuzooVn** [comment]
Thank you. Please make the Pull Request.

**Comment by ZuzooVn** [comment]
Thanks. I merged Pull Request #42
