### ISSUE TITLE
About these materials of ML

### ISSUE THREAD

**Issue by ShuyuanCao** [ZuzooVn/machine-learning-for-software-engineers#54]
May I ask did u finish reading through all these materials of Machine Learning in your Repo?

**Comment by bhavaniravi** [comment]
I did read through the materials initially it was over whelming later I
could clam myself down and took it slow.

I still didn't complete it. I have a theoretical understanding But I miss
the intuition of why's and how's, things to consider before choosing an
algo.

In progress will complete it soon.

**Comment by ShuyuanCao** [comment]
the same with me~
I am still in progress~

thanks.
