### ISSUE TITLE
Traditional Chinese(zh-TW) language support

### ISSUE THREAD

**Issue by NeroCube** [ZuzooVn/machine-learning-for-software-engineers#73]
Hi @ZuzooVn,This is an awesome project.
I hope more people can see .
I have completed the translation of Traditional Chinese and I have made a [PR](https://github.com/ZuzooVn/machine-learning-for-software-engineers/pull/72).
May you add the Traditional Chinese version on this repo?

**Comment by ZuzooVn** [comment]
I merged this commit.
Thanks
